#ifndef _GEM_BOOTLOADER_SETUP_
#define _GEM_BOOTLOADER_SETUP_

#include <Uefi.h>

#define GEM_LOG

#define GEM_WARNING_BIT 0x4000000000000000ULL
#define GEM_ERROR_BIT 0xC000000000000000ULL
#define GEM_ENCODE_WARNING(StatusCode) ((RETURN_STATUS)(GEM_WARNING_BIT | (StatusCode)))
#define GEM_ENCODE_ERROR(StatusCode) ((RETURN_STATUS)(GEM_ERROR_BIT | (StatusCode)))

#define GEM_ELF_CHECK_FAILED GEM_ENCODE_ERROR(1)
#define GEM_ELF_RELOCATE_FAILED GEM_ENCODE_ERROR(2)

#endif